In [1]:
pip install numpy

In [2]:
import numpy as np
print(np.__version__)

1.25.2


In [3]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [5]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.shape)

(2, 2, 2)


In [6]:
a=np.array([1,2,3,4,5])
print(a.size)

5


In [7]:
a=np.array([1,2,3,4,5])
print(a.dtype)

int64


In [8]:
b=np.array([1.0,2.0,3.0])
print(b.dtype)

float64


In [9]:
c=np.array([1+2j,3+4j])
print(c.dtype)

complex128


In [10]:
d=np.array([True,False,True])
print(d.dtype)

bool


In [11]:
a=np.array([1,2,3],dtype=np.float32)
print(a)
print(a.dtype)

[1. 2. 3.]
float32


In [12]:
b=np.array([1,2,3],dtype=np.int16)
print(b)
print(b.dtype)

[1 2 3]
int16


In [13]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
b=np.array((10,20,30))
print(b)

[10 20 30]


In [15]:
c=[1,2,3,4,5]
a=np.asarray(c)
print(a)

[1 2 3 4 5]


In [16]:
d=(10,20,30)
b=np.asarray(d)
print(b)

[10 20 30]


In [17]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [18]:
b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [20]:
b=np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a=np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [22]:
b=np.empty((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
b=np.arange(2,11,2)
print(b)

[ 2  4  6  8 10]


In [25]:
a=np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [26]:
b=np.linspace(0,10,9)
print(b)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [27]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [28]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [30]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=b-a
print(c)

[3 3 3]


In [31]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a*b
print(c)

[ 4 10 18]


In [32]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=b/a
print(c)

[4.  2.5 2. ]


In [33]:
a=np.array([1,2,3])
b=a*2
print(b)
c=a/2
print(c)

[2 4 6]
[0.5 1.  1.5]


In [34]:
a=np.array([1,4,9])
b=np.sqrt(a)
print(b)

[1. 2. 3.]


In [35]:
a=np.array([1,2,3])
b=np.exp(a)
print(b)

[ 2.71828183  7.3890561  20.08553692]


In [36]:
a=np.array([1,2,3])
b=2
c=a+b
print(c)

[3 4 5]


In [37]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
c=a+b
print(c)

[[11 22 33]
 [14 25 36]]


In [38]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2], [3,4],[5,6]])
c=a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [39]:
import time
a=np.random.rand(10000000)
b=np.random.rand(10000000)
start=time.time()
c=a+b
end=time.time()
print(f"NumPy element-wise addition took: {end-start:.6f} seconds")
start=time.time()
x=[i for i in range(10000000)]
y=[i for i in range(10000000)]
z=[x[i]+y[i] for i in range(10000000)]
end=time.time()
print(f"Python list element-wise addition took: {end-start:.6f} seconds")

NumPy element-wise addition took: 0.048119 seconds
Python list element-wise addition took: 4.613806 seconds


In [40]:
a=np.array([1,2,3,4,5])
print(a[0])
print(a[3])

1
4


In [41]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0,0])
print(b[2,1])

1
8


In [42]:
a=np.array([1,2,3,4,5])
indices=np.array([0,2,4])
print(a[indices])

[1 3 5]


In [43]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
rows=np.array([0,2])
cols=np.array([0,2])
print(b[rows,cols])

[1 9]


In [44]:
a=np.array([1,2,3,4,5])
print(a[a>3])

[4 5]


In [45]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[b>5])

[6 7 8 9]


In [46]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[2:6])
print(a[:4])
print(a[5:])
print(a[::2])
print(a[::-1])

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [47]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0:2,0:2])
print(b[:,1])
print(b[1:,:2])

[[1 2]
 [4 5]]
[2 5 8]
[[4 5]
 [7 8]]


In [48]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[::3])
print(a[::-2])

[1 4 7]
[9 7 5 3 1]


In [49]:
a=np.array([1,2,3,4,5])
a[1:4]=10
print(a)

[ 1 10 10 10  5]


In [50]:
a=np.array([1,2,3,4,5,6])
print(a.shape)
b=a.reshape(2,3)
print(b)
c=a.reshape(2,1,3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [51]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [52]:
c=np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [53]:
d=np.concatenate((a,b),axis=None)
print(d)

[1 2 3 4 5 6]


In [54]:
e=np.array([[1, 2],[3,4]])
f=np.array([[5, 6],[7,8]])
g=np.concatenate((e,f),axis=0)
print(g)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [55]:
a=np.array([1,2])
b=np.array([3,4])

In [56]:
c=np.hstack((a,b))
print(c)

[1 2 3 4]


In [57]:
d=np.vstack((a,b))
print(d)

[[1 2]
 [3 4]]


In [58]:
e=np.stack((a,b),axis=1)
print(e)

[[1 3]
 [2 4]]


In [59]:
a=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

In [60]:
left,right=np.hsplit(a,2)
print("Horizontal split:")
print("Left sub-array:\n",left)
print("Right sub-array:\n",right)

Horizontal split:
Left sub-array:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Right sub-array:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [61]:
a=np.array([1,2,3])
b=np.append(a,[4,5])
print(b)
c=np.array([[1,2],[3,4]])
d=np.append(c,[[5,6]],axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [62]:
a=np.array([1,2,3,4,5])
b=np.insert(a,2,[10,20])
print(b)
c=np.array([[1,2],[3,4]])
d=np.insert(c,1,[10,20],axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [63]:
a=np.array([1,2,3,4,5])
b=np.delete(a,[0,2])
print(b)
c=np.array([[1,2,3],[4,5,6]])
d=np.delete(c,1,axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


In [64]:
a=np.array([1,2,3,4,5])
b=np.resize(a,(3,3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


# EXERCISE

# Array Operations and Broadcasting:

In [65]:
a=np.random.rand(2,3,4)
b=np.random.rand(3,4)

[[[0.04126935 0.00213087 0.12270021 0.22719417]
  [0.83253441 0.10799183 0.47123165 0.11917008]
  [0.47302612 0.54756532 0.0941427  0.17650126]]

 [[0.01852324 0.00482669 0.30432122 0.00530553]
  [0.45113226 0.16335904 0.23754755 0.18495681]
  [0.15688604 0.72915501 0.03382493 0.12397554]]]


In [66]:
result_mult=a*b
print("Result of element-wise multiplication:")
print(result_mult)

Result of element-wise multiplication:
[[[0.04126935 0.00213087 0.12270021 0.22719417]
  [0.83253441 0.10799183 0.47123165 0.11917008]
  [0.47302612 0.54756532 0.0941427  0.17650126]]

 [[0.01852324 0.00482669 0.30432122 0.00530553]
  [0.45113226 0.16335904 0.23754755 0.18495681]
  [0.15688604 0.72915501 0.03382493 0.12397554]]]


In [68]:
def elementwise_operations(c,d):
    try:
        add=c+d
        sub=c-d
        mul=c*d
        div=c/d
    except ValueError as e:
        return f"Broadcasting not possible: {e}"
    return {'addition':add,'subtraction':sub,'multiplication':mul,'division':div}

In [70]:
c=np.random.rand(4,3)
d=np.random.rand(4,1)

In [71]:
operations_result=elementwise_operations(c,d)
print("Element-wise operations results:")
print(operations_result)

Element-wise operations results:
{'addition': array([[0.42069045, 0.38179358, 0.68454246],
       [1.09482509, 1.4958976 , 0.78145945],
       [0.65256949, 0.90038644, 1.18709466],
       [1.38400107, 0.853293  , 0.83983863]]), 'subtraction': array([[-0.30124777, -0.34014464, -0.03739577],
       [-0.15122023,  0.24985227, -0.46458587],
       [-0.5464012 , -0.29858426, -0.01187604],
       [ 0.52626502, -0.00444305, -0.01789742]]), 'multiplication': array([[0.02155756, 0.00751699, 0.11679998],
       [0.29394361, 0.54382087, 0.09870971],
       [0.03182317, 0.18038579, 0.35226317],
       [0.40962602, 0.1820223 , 0.17625215]]), 'division': array([[0.16544723, 0.05769045, 0.89640174],
       [0.75727972, 1.4010324 , 0.25430341],
       [0.08854953, 0.50193235, 0.98018961],
       [2.22710249, 0.98964006, 0.95826824]])}


In [72]:
e=np.random.rand(5,3)
f=np.random.rand(5)

In [73]:
outer_product=e*f[:,np.newaxis]
print("Outer product result:")
print(outer_product)

Outer product result:
[[0.0979397  0.0727106  0.33550697]
 [0.21782067 0.94882788 0.63259068]
 [0.46337776 0.20161379 0.18657886]
 [0.08256771 0.01061222 0.04474998]
 [0.10590894 0.63476134 0.26987018]]


# Indexing and Slicing:

In [74]:
g=np.random.rand(4,3,2)
extracted_g=g[::2,::2,:]
print("Extracted array:")
print(extracted_g)

Extracted array:
[[[0.55802769 0.87751225]
  [0.58879221 0.41433534]]

 [[0.69395524 0.74554015]
  [0.5943081  0.64958989]]]


In [75]:
def sum_diagonals(h,i,j):
    k=np.zeros((len(i),len(j)))
    for m in range(len(i)):
        for n in range(len(j)):
            k[m,n]=np.sum(np.diag(h,j[n]-i[m]))
    return k


In [76]:
h=np.random.rand(4,4)
i=np.array([0,1])
j=np.array([0,2])

In [77]:
k=sum_diagonals(h,i,j)
print("Sum of diagonals result:")
print(k)

Sum of diagonals result:
[[2.60648246 1.03344197]
 [1.93640932 1.40486077]]


In [78]:
def product_of_means(l):
    row_means=l.mean(axis=1,keepdims=True)
    col_means=l.mean(axis=0,keepdims=True)
    m=row_means*col_means
    return m


In [79]:
l=np.random.rand(4,5)

In [80]:
m=product_of_means(l)
print("Product of row and column means result:")
print(m)

Product of row and column means result:
[[0.14203389 0.17227075 0.07657105 0.18178394 0.20619842]
 [0.22253516 0.26990951 0.11996961 0.28481454 0.32306654]
 [0.23286018 0.28243258 0.12553587 0.29802917 0.33805595]
 [0.19774221 0.23983852 0.10660363 0.25308297 0.28707325]]


# Array Manipulation:

In [81]:
n=np.random.rand(4,6)

In [82]:
reshaped_n=n.reshape(2,2,6)
print("Reshaped array:")
print(reshaped_n)

Reshaped array:
[[[0.60912829 0.53257333 0.01695701 0.17279767 0.79297443 0.00834945]
  [0.42488784 0.52396447 0.90693231 0.6541206  0.7111498  0.67957573]]

 [[0.26980829 0.77910305 0.70385754 0.0884263  0.59548637 0.67702846]
  [0.84337879 0.1644518  0.79926233 0.33073107 0.29565201 0.4078173 ]]]


In [83]:
flattened_n=reshaped_n.reshape(4,6)
print("Flattened back to original shape:")
print(flattened_n)

Flattened back to original shape:
[[0.60912829 0.53257333 0.01695701 0.17279767 0.79297443 0.00834945]
 [0.42488784 0.52396447 0.90693231 0.6541206  0.7111498  0.67957573]
 [0.26980829 0.77910305 0.70385754 0.0884263  0.59548637 0.67702846]
 [0.84337879 0.1644518  0.79926233 0.33073107 0.29565201 0.4078173 ]]


In [84]:
def roll_array(o,positions):
    return np.roll(o,positions,axis=0)

In [85]:
o=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
positions=2

In [86]:
rolled_o=roll_array(o,positions)
print("Rolled array:")
print(rolled_o)

Rolled array:
[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


In [87]:
def replace_with_mean(p,x):
    p=p.copy()
    rows, cols=p.shape
    for i in range(rows):
        for j in range(cols):
            if p[i,j]==x:
                neighbors=[]
                if i>0:
                    neighbors.append(p[i-1,j])
                if i<rows-1:
                    neighbors.append(p[i+1,j])
                if j>0:
                    neighbors.append(p[i,j-1])
                if j<cols-1:
                    neighbors.append(p[i,j+1])
                if neighbors:
                    p[i,j]=np.mean(neighbors)
    return p

In [88]:
p=np.array([[1,2,3],[4,5,6], [7,8,5],[10,11,12]])
x=5

In [89]:
replaced_p=replace_with_mean(p,x)
print("Array with replacements:")
print(replaced_p)

Array with replacements:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  8]
 [10 11 12]]
